[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = {workspace = true}
tantivy-jieba = {workspace = true}
chrono = {workspace = true,features = ["serde"]}
serde_json = {workspace=true}
uuid = {workspace = true,features = ["serde"]}
serde = {workspace = true}
