[package]
name = "cli"
version = "0.1.0"
edition = "2021"
default-run = "cli"

[dependencies]
tokio={workspace=true,features = ["rt-multi-thread","macros"]}
server={workspace=true}
anyhow={workspace=true}